name: upi_payment_callback_handler
description: "A Flutter plugin to launch UPI apps via intent link or deeplink and listen for payment callback events on Android and iOS."
version: 0.0.1
homepage: https://github.com/Lalit-Kumar-1031/upi_payment_callback_handler
repository: https://github.com/Lalit-Kumar-1031/upi_payment_callback_handler
issue_tracker: https://github.com/Lalit-Kumar-1031/upi_payment_callback_handler/issues


environment:
  sdk: ^3.11.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.upi_payment_callback_handler
        pluginClass: UpiPaymentCallbackHandlerPlugin
      ios:
        pluginClass: SwiftUpiPaymentCallbackHandlerPlugin

 